"""FiedlerEnsemble: algebraic redistricting + MCMC outlier detection.

The Python package is imported as ``gerrydetect`` for backwards-compatibility,
but the project's external name (repo, papers, README) is **FiedlerEnsemble**:

- *Fiedler* — the eigenvector of the second-smallest Laplacian eigenvalue,
  used in the deterministic spectral-bisection baseline.
- *Ensemble* — large set of alternative plans generated by single-flip
  Metropolis-Hastings MCMC, against which the enacted plan is scored.

NETS 1500 final project, Spring 2026.
"""

from gerrydetect.partition import MutablePartition, Partition

__all__ = ["Partition", "MutablePartition"]
__version__ = "0.1.0"
